from typing import List, Tuple

soccer_db: List[Tuple[str, str, str, str, int]] = [
    (
        "Lionel Messi",  # player name
        "Forward",  # position
        "Inter Miami",  # club
        "Argentina",  # nationality
        800,  # goals
    ),
    (
        "Cristiano Ronaldo",
        "Forward",
        "Al Nassr",
        "Portugal",
        850,
    ),
    (
        "Neymar Jr.",
        "Forward",
        "Al Hilal",
        "Brazil",
        400,
    ),
    (
        "Kylian Mbappé",
        "Forward",
        "Paris Saint-Germain",
        "France",
        250,
    ),
    (
        "Robert Lewandowski",
        "Forward",
        "Barcelona",
        "Poland",
        700,
    ),
    (
        "Kevin De Bruyne",
        "Midfielder",
        "Manchester City",
        "Belgium",
        100,
    ),
    (
        "Mohamed Salah",
        "Forward",
        "Liverpool",
        "Egypt",
        250,
    ),
    (
        "Karim Benzema",
        "Forward",
        "Al Ittihad",
        "France",
        400,
    ),
    (
        "Gareth Bale",
        "Forward",
        "Retired",
        "Wales",
        200,
    ),
    (
        "Zlatan Ibrahimović",
        "Forward",
        "Retired",
        "Sweden",
        500,
    ),
    (
        "Luis Suárez",
        "Forward",
        "Grêmio",
        "Uruguay",
        500,
    ),
    (
        "Sadio Mané",
        "Forward",
        "Al Nassr",
        "Senegal",
        200,
    ),
    (
        "Son Heung-min",
        "Forward",
        "Tottenham Hotspur",
        "South Korea",
        150,
    ),
    (
        "Eden Hazard",
        "Forward",
        "Retired",
        "Belgium",
        100,
    ),
    (
        "Harry Kane",
        "Forward",
        "Bayern Munich",
        "England",
        300,
    ),
    (
        "Virgil van Dijk",
        "Defender",
        "Liverpool",
        "Netherlands",
        30,
    ),
    (
        "N'Golo Kanté",
        "Midfielder",
        "Al Ahli",
        "France",
        20,
    ),
    (
        "Kante Koulibaly",
        "Defender",
        "Al Nassr",
        "Senegal",
        15,
    ),
    (
        "Alphonso Davies",
        "Defender",
        "Bayern Munich",
        "Canada",
        15,
    ),
    (
        "Gavi",
        "Midfielder",
        "Barcelona",
        "Spain",
        10,
    ),
    (
        "Pedri",
        "Midfielder",
        "Barcelona",
        "Spain",
        10,
    ),
    (
        "Declan Rice",
        "Midfielder",
        "Arsenal",
        "England",
        10,
    ),
    (
        "Phil Foden",
        "Midfielder",
        "Manchester City",
        "England",
        20,
    ),
]
